# https://taskfile.dev

version: '3'

dotenv: [".env"]

# vars:
#   BOARD: p3509-a02+p3767-0000
#   RUNTIME: ${RUNTIME}
#   VERSION: R35.2.1

tasks:
  default:
    cmds:
      - task -l
    silent: true

  show-args:
    desc: "show available commands from sdkmanager"
    cmds:
      - sdkmanager --query

  download:
    desc: "download packages"
    cmds:
      - |
        sdkmanager --cli downloadonly --logintype devzone --product Jetson --version ${JETPACK_VERSION} --targetos Linux --target ${TARGET} \
        --select 'Jetson Linux' \
        --deselect 'Jetson SDK Components' \
        --deselect 'Developer Tools' \
        --deselect 'Developer Tools for Deep Learning' \
        --deselect 'Jetson Runtime Components' \
        --license accept \
        --staylogin true \
        --datacollection disable
      #- docker compose run --rm sdkmanager --cli downloadonly --responsefile /sdkm_responsefile_jetson.ini

  build:
    desc: "build orin image"
    cmds:
      - |
        sudo rm -fR ~/nvidia #~/.nvsdkm
        sdkmanager --cli install --logintype devzone --license accept --staylogin true --exitonfinish --datacollection disable --product Jetson --version ${JETPACK_VERSION} \
        --targetos Linux \
        --target ${TARGET} \
        --select 'Jetson Linux' \
        --deselect 'Jetson SDK Components' \
        --deselect 'Developer Tools' \
        --deselect 'Developer Tools for Deep Learning' \
        --deselect 'Jetson Runtime Components' \
        --offline \
        --downloadfolder $HOME/Downloads/nvidia/sdkm_downloads/ \
        --flash skip
        #- docker compose run sdkmanager --cli install --responsefile /sdkm_responsefile_jetson.ini
        ln -sf $HOME/nvidia/nvidia_sdk/JetPack_${JETPACK_VERSION}_Linux_${TARGET}/Linux_for_Tegra/ /home/nvidia/tegra

        # sdkmanager --cli install --logintype devzone --product Jetson --version 5.1 --targetos Linux --host --target JETSON_AGX_ORIN_TARGETS --flash all --additionalsdk 'DeepStream 6.2'
